import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import LoginChecker from "./LoginChecker";
import axios from "axios"
import Head from "next/head";
export const metadata: Metadata = {
  title: "Application Tracking System",
  description: "Generated by create next app",
};

axios.defaults.withCredentials = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon" />
      </Head>
      <body className="">
        <StoreProvider>
          <LoginChecker>
            {children}
          </LoginChecker>
        </StoreProvider>
      </body>
    </html>
  );
}
