import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import axios from "axios"
export const metadata: Metadata = {
  title: "Application Tracking System",
  description: "Generated by create next app",
};

axios.defaults.withCredentials = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
